//
//  FlagDataStore.swift
//  Hangman Classic
//
//  Created by M I C H A E L on 25.04.2023.
//

class FlagDataStore {
    
    let flagsAndCourties = [
        "Арабские Эмираты": "UAE",
        "Афганистан": "Afghanistan",
        "ALL": "Albania",
        "AMD": "Armenia",
        "ANG": "Curacao",
        "AOA": "Angola",
        "ARS": "Argentina",
        "AUD": "Australia",
        "AWG": "Aruba",
        "AZN": "Azerbaijan",
        "BAM": "Bosnia & Herzegovina",
        "BBD": "Barbados",
        "BDT": "Bangladesh",
        "BGN": "Bulgaria",
        "BHD": "Bahrain",
        "BIF": "Burundi",
        "BMD": "Bermuda",
        "BND": "Brunei",
        "BOB": "Bolivia",
        "BRL": "Brazil",
        "BSD": "Bahamas",
        "BTN": "Bhutan",
        "BWP": "Botswana",
        "BZD": "Belize",
        "CAD": "Canada",
        "CDF": "Congo",
        "CHF": "Switzerland",
        "CNY": "China",
        "COP": "Colombia",
        "CRC": "Costa Rica",
        "CVE": "Cabo Verde Escudo",
        "CZK": "Czech Republic",
        "DJF": "Djibouti",
        "DKK": "Denmark",
        "DOP": "Dominican Republic",
        "DZD": "Algeria",
        "EGP": "Egypt",
        "ERN": "Eritrea",
        "ETB": "Ethiopia",
        "EUR": "European Union",
        "FJD": "Fiji",
        "FKP": "Falkland Islands",
        "GBP": "United Kingdom",
        "GEL": "Georgia",
        "GGP": "Guernsey",
        "GHS": "Ghana",
        "GIP": "Gibraltar",
        "GMD": "Gambia",
        "GNF": "Guinea",
        "GTQ": "Guatemala",
        "GYD": "Guyana",
        "HNL": "Honduras",
        "HRK": "Croatia",
        "HTG": "Haiti",
        "HUF": "Hungary",
        "IDR": "Indonesia",
        "ILS": "Israel",
        "IMP": "Isle of Man",
        "INR": "India",
        "IQD": "Iraq",
        "IRR": "Iran",
        //"ISK": "Iceland", // НЕТ ФОТО
        "JEP": "Jersey",
        "JMD": "Jamaica",
        "JOD": "Jordan",
        "JPY": "Japan",
        "KES": "Kenya",
        "KGS": "Kyrgyzstan",
        "KHR": "Cambodia",
        "KMF": "Comoros",
        "KPW": "Korea (North)",
        "KRW": "Korea (South)",
        "KWD": "Kuwait",
        "KYD": "Cayman Islands",
        "KZT": "Kazakhstan",
        "LAK": "Laos",
        "LBP": "Lebanon",
        "LKR": "Sri Lanka",
        "LRD": "Liberia",
        "LSL": "Lesotho",
        "LTL": "Lithuania",
        "LVL": "Latvia",
        "LYD": "Libya",
        "MAD": "Morocco",
        "MDL": "Moldova",
        "MGA": "Madagascar",
        "MKD": "Macedonia",
        "MMK": "Myanmar (Burma)",
        "MNT": "Mongolia",
        "MOP": "Macau",
        "MUR": "Mauritius",
        "MVR": "Maldives",
        "MWK": "Malawi",
        "MXN": "Mexico",
        "MYR": "Malaysia",
        "MZN": "Mozambique",
        "NAD": "Namibia",
        "NGN": "Nigeria",
        "NIO": "Nicaragua",
        "NOK": "Norway",
        "NPR": "Nepal",
        "NZD": "New Zealand",
        "OMR": "Oman",
        "PAB": "Panama",
        "PEN": "Peru",
        "PGK": "Papua New Guinea",
        "PHP": "Philippines",
        "PKR": "Pakistan",
        "PLN": "Poland",
        "PYG": "Paraguay",
        "QAR": "Qatar",
        "RON": "Romania",
        "RSD": "Serbia",
        "RUB": "Russia",
        "RWF": "Rwanda",
        "SAR": "Saudi Arabia",
        "SBD": "Solomon Islands",
        "SCR": "Seychelles",
        "SDG": "Sudan",
        "SEK": "Sweden",
        "SGD": "Singapore",
        "SHP": "Saint Helena",
        "SLL": "Sierra Leone",
        "SOS": "Somalia",
        "SRD": "Suriname",
        "SVC": "El Salvador",
        "SYP": "Syria",
        "SZL": "Eswatini",
        "THB": "Thailand",
        "TJS": "Tajikistan",
        "TMT": "Turkmenistan",
        "TND": "Tunisia",
        "TOP": "Tonga",
        "TRY": "Turkey",
        "TTD": "Trinidad & Tobago",
        "TWD": "Taiwan",
        "TZS": "Tanzania",
        "UAH": "Ukraine",
        "UGX": "Uganda",
        "USD": "United States",
        "UYU": "Uruguay",
        "UZS": "Uzbekistan",
        "VEF": "Venezuela",
        "VND": "Vietnam",
        "VUV": "Vanuatu",
        "WST": "Samoa",
        "XCD": "Caribbean Netherlands",
        "YER": "Yemen",
        "ZAR": "South Africa",
        "ZMK": "Zambia",
        "CUC": "Cuba",
        "CLP": "Chile",
        "BYN": "Belarus",
        "MRO": "Mauritania"
    ]
}
